spring:
   ## MySQL
  datasource:
    url: jdbc:mysql://192.168.****:3306/hddoc?useUnicode=true&amp;characterEncoding=UTF-8
    username: ****
    password: *****
    driver-class-name: com.mysql.jdbc.Driver

 ## Redis配置
redis:
    host: 192.168.1****
    port: ****
    timeout: 10000
    pool:
          max-idle: 10
          min-idle: 1
          max-active: 10
          max-wait: -1


log:
  config: classpath:logback-spring.xml
  loggingRoot: /Users/dongliangyu/WorkSpace/logs
  loggingLevel: debug
