spring:
   ## MySQL
  datasource:
    url: jdbc:mysql://192.168.11.212:3306/hddoc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: hddoc
    password: Hd_Mysql5718
    driver-class-name: com.mysql.jdbc.Driver

log:
 config: classpath:logback-spring.xml
  loggingRoot: /Users/dongliangyu/WorkSpace/logs
  loggingLevel: debug
